x-logging: &x-logging
  logging:
    driver: json-file
    options:
      max-file: "5"
      max-size: 10m

services:
  traefik:
    image: traefik:3.6
    <<: *x-logging
    restart: unless-stopped
    command:
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.appwrite_web.address=:80
      - --entrypoints.appwrite_websecure.address=:443
      - --entryPoints.appwrite_web.forwardedHeaders.insecure
      - --entryPoints.appwrite_websecure.forwardedHeaders.insecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - appwrite-config:/storage/config:ro
      - appwrite-certificates:/storage/certificates:ro
    depends_on:
      - appwrite
    networks:
      - appwrite

  appwrite:
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -fsS -o /dev/null -H "Host: appwrite.pdnode.com" http://localhost/v1/health/version'
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 120s
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_api.loadbalancer.server.port=80
      - traefik.http.routers.appwrite_api_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_api_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_http.service=appwrite_api
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-imports:/storage/imports:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - redis
      - postgresql
      - appwrite-embedding
      - appwrite-geo
    environment:
      - _APP_ENV
      - _APP_USAGE_STATS
      - _APP_USAGE_PASS
      - _APP_CONNECTIONS_DB_USAGE
      - _APP_POOL_SIZE_USAGE
      - _APP_EXECUTIONS_DUAL_WRITE
      - _APP_CONNECTIONS_DB_EXECUTIONS
      - _APP_POOL_SIZE_EXECUTIONS
      - _APP_EDITION
      - _APP_WORKER_PER_CORE
      - _APP_POOL_ADAPTER
      - _APP_LOCALE
      - _APP_COMPRESSION_ENABLED
      - _APP_COMPRESSION_MIN_SIZE_BYTES
      - _APP_CONSOLE_WHITELIST_ROOT
      - _APP_CONSOLE_WHITELIST_EMAILS
      - _APP_CONSOLE_HOSTNAMES
      - _APP_CONSOLE_SCHEMA
      - _APP_SYSTEM_EMAIL_NAME
      - _APP_SYSTEM_EMAIL_ADDRESS
      - _APP_OPTIONS_ABUSE
      - _APP_OPTIONS_ROUTER_PROTECTION
      - _APP_OPTIONS_FORCE_HTTPS
      - _APP_OPTIONS_ROUTER_FORCE_HTTPS
      - _APP_OPENSSL_KEY_V1
      - _APP_NOTIFICATIONS_TRACKING_SECRET
      - _APP_DOMAIN
      - _APP_CONSOLE_DOMAIN
      - _APP_TRUSTED_HEADERS
      - _APP_DOMAIN_TARGET_CNAME
      - _APP_DOMAIN_TARGET_A
      - _APP_DOMAIN_FUNCTIONS
      - _APP_DOMAIN_SITES
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_SMTP_HOST
      - _APP_SMTP_PORT
      - _APP_SMTP_SECURE
      - _APP_SMTP_USERNAME
      - _APP_SMTP_PASSWORD
      - _APP_STORAGE_LIMIT
      - _APP_STORAGE_PREVIEW_LIMIT
      - _APP_STORAGE_ANTIVIRUS
      - _APP_STORAGE_DEVICE
      - _APP_COMPUTE_SIZE_LIMIT
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_SITES_TIMEOUT
      - _APP_COMPUTE_BUILD_TIMEOUT
      - _APP_COMPUTE_CPUS
      - _APP_COMPUTE_MEMORY
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_SITES_RUNTIMES
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_BUILDS_VOLUME
      - _APP_JOBS_HOST
      - _APP_JOBS_SECRET
      - _APP_JOBS_ENDPOINT
      - _APP_GEO_SECRET
      - _APP_GEO_ENDPOINT
      - _APP_MIGRATION_HOST
      - _APP_USAGE_STATS
      - _APP_CONNECTIONS_DB_USAGE
      - _APP_CONNECTIONS_DB_EXECUTIONS

  appwrite-console:
    <<: *x-logging
    image: appwrite/new:1.1.8
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - VITE_CONSOLE_PROFILE=self-hosted
      - APPWRITE_ENDPOINT_SAME_ORIGIN=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_console.loadbalancer.server.port=3000
      - traefik.http.routers.appwrite_console_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_console_http.rule=(Host(`appwrite.pdnode.com`)) && !PathPrefix(`/v1`) && !PathPrefix(`/.well-known`)
      - traefik.http.routers.appwrite_console_http.service=appwrite_console

  appwrite-realtime:
    entrypoint: realtime
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_realtime.loadbalancer.server.port=80
      - traefik.http.routers.appwrite_realtime_ws.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_realtime_ws.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_ws.service=appwrite_realtime
    networks:
      - appwrite
    depends_on:
      - postgresql
      - redis
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_CONSOLE_HOSTNAMES
      - _APP_REALTIME_TAIL_RATE
      - _APP_POOL_ADAPTER=swoole
      - _APP_USAGE_STATS
      - _APP_STATS_USAGE_QUEUE_NAME
      - _APP_OPTIONS_ABUSE
      - _APP_OPTIONS_ROUTER_PROTECTION

  appwrite-worker:
    entrypoint: worker
    restart: unless-stopped
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    networks:
      - appwrite
    depends_on:
      - redis
      - postgresql
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-config:/storage/config:rw
      - appwrite-imports:/storage/imports:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - _APP_ENV
      - _APP_WORKERS_NUM=1
      - _APP_WORKER_MAX_COROUTINES=78
      - _APP_OPENSSL_KEY_V1
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DOMAIN
      - _APP_CONSOLE_DOMAIN
      - _APP_DOMAIN_FUNCTIONS
      - _APP_DOMAIN_SITES
      - _APP_OPTIONS_FORCE_HTTPS
      - _APP_EXECUTOR_SECRET
      - _APP_EXECUTOR_HOST
      - _APP_JOBS_HOST
      - _APP_JOBS_SECRET
      - _APP_JOBS_ENDPOINT
      - _APP_BUILDS_VOLUME
      - _APP_STORAGE_DEVICE
      - _APP_USAGE_STATS
      - _APP_USAGE_PASS
      - _APP_CONNECTIONS_DB_USAGE
      - _APP_CONNECTIONS_DB_EXECUTIONS

  appwrite-task-scheduler:
    entrypoint: schedule
    restart: unless-stopped
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    networks:
      - appwrite
    depends_on:
      - postgresql
      - redis
    environment:
      - _APP_ENV
      - _APP_WORKER_MAX_COROUTINES=8
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN
      - _APP_CONSOLE_DOMAIN
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS

  appwrite-task-maintenance:
    entrypoint: maintenance
    restart: unless-stopped
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    networks:
      - appwrite
    depends_on:
      - postgresql
      - redis
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_DOMAIN

  appwrite-task-interval:
    entrypoint: interval
    restart: unless-stopped
    <<: *x-logging
    image: appwrite/appwrite:2.0.0
    networks:
      - appwrite
    depends_on:
      - postgresql
      - redis
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_DB_ADAPTER
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_DOMAIN

  appwrite-browser:
    image: appwrite/browser:0.3.4
    restart: unless-stopped
    networks:
      - appwrite

  clickhouse:
    image: clickhouse/clickhouse-server:26.4.3-alpine
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - CLICKHOUSE_DB=appwrite
      - CLICKHOUSE_USER=appwrite
      - CLICKHOUSE_PASSWORD=appwrite
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - appwrite-clickhouse:/var/lib/clickhouse:rw
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  appwrite-geo:
    <<: *x-logging
    image: appwrite/geo:0.3.1
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - GEO_SECRET=${_APP_GEO_SECRET}

  openruntimes-executor:
    hostname: exc1
    <<: *x-logging
    stop_signal: SIGINT
    image: openruntimes/executor:0.29.0
    restart: unless-stopped
    networks:
      - appwrite
      - runtimes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-builds:/storage/builds:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - /tmp:/tmp:rw
    environment:
      - OPR_EXECUTOR_IMAGES=${_APP_EXECUTOR_IMAGES}
      - OPR_EXECUTOR_INACTIVE_THRESHOLD=${_APP_COMPUTE_INACTIVE_THRESHOLD}
      - OPR_EXECUTOR_MAINTENANCE_INTERVAL=${_APP_COMPUTE_MAINTENANCE_INTERVAL}
      - OPR_EXECUTOR_NETWORK=${_APP_COMPUTE_RUNTIMES_NETWORK}
      - OPR_EXECUTOR_ENV=${_APP_ENV}
      - OPR_EXECUTOR_RUNTIMES=${_APP_FUNCTIONS_RUNTIMES},${_APP_SITES_RUNTIMES}
      - OPR_EXECUTOR_SECRET=${_APP_EXECUTOR_SECRET}
      - OPR_EXECUTOR_RUNTIME_VERSIONS=v5
      - OPEN_RUNTIMES_NFT=${_APP_OPEN_RUNTIMES_NFT}
      - OPR_EXECUTOR_CONNECTION_STORAGE=local://localhost

  orchestrator:
    hostname: orchestrator
    <<: *x-logging
    image: ghcr.io/open-runtimes/orchestrator/orchestrator:1.9.2
    restart: unless-stopped
    user: root
    networks:
      - appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ORCHESTRATOR_BACKEND=docker
      - ORCHESTRATOR_NETWORK=appwrite
      - DOCKER_NETWORK=appwrite
      - ARTIFACT_ENDPOINT=http://orchestrator:8080

  postgresql:
    image: appwrite/postgres:0.1.0
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-postgresql:/var/lib/postgresql:rw
    environment:
      - POSTGRES_DB=${_APP_DB_SCHEMA}
      - POSTGRES_USER=${_APP_DB_USER}
      - POSTGRES_PASSWORD=${_APP_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  appwrite-embedding:
    image: appwrite/embedding:0.1.0
    restart: unless-stopped
    environment:
      EMBEDDING_MODELS: ${_APP_EMBEDDING_MODELS:-nomic-embed-text}
    volumes:
      - appwrite-models:/home/embedder/models
    networks:
      - appwrite

  redis:
    image: redis:7.4.7-alpine
    <<: *x-logging
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--maxmemory",
        "512mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

networks:
  appwrite:
    name: appwrite
  runtimes:
    name: runtimes

volumes:
  appwrite-postgresql:
  appwrite-redis:
  appwrite-cache:
  appwrite-clickhouse:
  appwrite-uploads:
  appwrite-imports:
  appwrite-certificates:
  appwrite-functions:
  appwrite-sites:
  appwrite-builds:
    name: appwrite-builds
  appwrite-config:
  appwrite-models:
